disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - force_cast

opt_in_rules: # Find all the available rules by running: swiftlint rules
  - empty_count

included: # paths to include during linting. `--path` is ignored if present.
  - ./
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

force_try:
  severity: warning # explicitly

trailing_whitespace: 
  ignores_empty_lines: true
vertical_whitespace:
  max_empty_lines: 2

line_length: 300

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 1000
  error: 1200

type_name:
  min_length: 4 # only warning
  max_length: 
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50 
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
